### ISSUE TITLE
Ubuntu 16.04 Build Failure

### ISSUE THREAD

**Issue by virtopiarvn** [stockmind/dell-xps-9560-ubuntu-respin#47]
You are about to add the following PPA:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1557, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 141, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 546, in add_proc_info
    self['ExecutablePath'] = os.readlink('/proc/' + pid + '/exe')
FileNotFoundError: [Errno 2] No such file or directory: '/proc/15564/exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 549, in add_proc_info
    raise ValueError('invalid process')
ValueError: invalid process

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1557, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 141, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
./isorespin.sh: Adding repository 'ppa:graphics-drivers/ppa' failed.

Trying to build on a Ubuntu 16.04 for Linux Mint "Tara" x64 no -k flag used. I also tried building on Ubuntu 18.04 and had the same error.

**Comment by stockmind** [comment]
Sorry i didn't follow this post, I've updated isorespin script!
Try and let me know!
Also i'm afraid that 16.04 is just a bit too old
