### ISSUE TITLE
Error during ISO building with Linux Mint 19.1 (using docker)

### ISSUE THREAD

**Issue by Bogardo** [stockmind/dell-xps-9560-ubuntu-respin#49]
```
$ ./docker-respin.sh origin/linuxmint-19.1-cinnamon-64bit.iso -c bionicbeaver 

Found Docker Hub image!
Iso: linuxmint-19.1-cinnamon-64bit.iso
Input dir: /home/<user>/dell-xps-9560-ubuntu-respin/origin
Output dir: /home/<user>/dell-xps-9560-ubuntu-respin/destination
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
default via 172.17.0.1 dev eth0 172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2
Gateway: 172.17.0.1
Internet test passed.
Images found in folder:
linuxmint-19.1-cinnamon-64bit.iso  readme.md  ubuntu-18.04.1-desktop-amd64.iso
Starting process...
Kernel arguments found!
respin linuxmint-19.1-cinnamon-64bit.iso -c bionicbeaver
./build.sh linuxmint-19.1-cinnamon-64bit.iso -c bionicbeaver --docker
Setting compatibility...
Called from docker...
isorespin.sh -i /docker-input/linuxmint-19.1-cinnamon-64bit.iso
Extracting ISO ...
Parallel unsquashfs: Using 8 processors
241107 inodes (261597 blocks) to write

[=======================================================================================================================================================================================================================|] 261597/261597 100%

created 176381 files
created 21124 directories
created 64616 symlinks
created 81 devices
created 0 fifos
Extracting isorespin files ...
Processing bootloader/bootmanager ...
Fetching mainline kernel packages ...
Installing mainline kernel packages ...
Adding repositories ...
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
You are about to add the following PPA:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1689, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 143, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 546, in add_proc_info
    self['ExecutablePath'] = os.readlink('/proc/' + pid + '/exe')
FileNotFoundError: [Errno 2] No such file or directory: '/proc/19195/exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 549, in add_proc_info
    raise ValueError('invalid process')
ValueError: invalid process

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1689, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 143, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
./isorespin.sh: Adding repository 'ppa:graphics-drivers/ppa' failed.
```

**Comment by arjenveenhuizen** [comment]
I just ran into the same problem, but while building on my local host without docker.
```
./build.sh linuxmint-19.1-cinnamon-64bit.iso -c bionicbeaver 
Setting compatibility...
isorespin.sh -i linuxmint-19.1-cinnamon-64bit.iso
Extracting ISO ...
Parallel unsquashfs: Using 8 processors
241107 inodes (261597 blocks) to write

[=========================================================\] 261597/261597 100%

created 176381 files
created 21124 directories
created 64616 symlinks
created 81 devices
created 0 fifos
Extracting isorespin files ...
Processing bootloader/bootmanager ...
Fetching mainline kernel packages ...
Installing mainline kernel packages ...
Adding repositories ...
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
You are about to add the following PPA:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1689, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 143, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport/report.py", line 546, in add_proc_info
    self['ExecutablePath'] = os.readlink('/proc/' + pid + '/exe')
FileNotFoundError: [Errno 2] No such file or directory: '/proc/29431/exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 549, in add_proc_info
    raise ValueError('invalid process')
ValueError: invalid process

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1689, in <module>
    add_repository_via_cli(ppa_line, codename, options.forceYes, use_ppas)
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 143, in add_repository_via_cli
    print(" %s" % (ppa_info["description"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 919-922: ordinal not in range(128)
./isorespin.sh: Adding repository 'ppa:graphics-drivers/ppa' failed.
```
